server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    add_header Cache-Control "no-store";

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /cosmos-rpc/ {
        proxy_pass http://validator-0:26657/;
    }

    location = /evm-rpc {
        proxy_pass http://validator-0:8545/;
    }

    location ~ ^/kudora-local-(config|wallets)\.json$ {
        try_files $uri =404;
    }
}
